/*
 * This source file was generated by the Gradle 'init' task
 */
package org.theunit;

import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.*;

import java.time.Duration;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.DisplayNameGeneration;
import org.junit.jupiter.api.DisplayNameGenerator;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.RepeatedTest;
import org.junit.jupiter.api.RepetitionInfo;
import org.junit.jupiter.api.condition.DisabledIf;
import org.junit.jupiter.api.condition.EnabledIf;
import org.junit.jupiter.api.extension.AnnotatedElementContext;
import org.junit.jupiter.params.ArgumentCountValidationMode;
import org.junit.jupiter.params.Parameter;
import org.junit.jupiter.params.ParameterizedClass;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.aggregator.AggregateWith;
import org.junit.jupiter.params.aggregator.ArgumentsAccessor;
import org.junit.jupiter.params.aggregator.SimpleArgumentsAggregator;
import org.junit.jupiter.params.converter.ConvertWith;
import org.junit.jupiter.params.converter.SimpleArgumentConverter;
import org.junit.jupiter.params.provider.CsvFileSource;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.EmptySource;
import org.junit.jupiter.params.provider.EnumSource;
import org.junit.jupiter.params.provider.NullSource;
import org.junit.jupiter.params.provider.ValueSource;

@DisplayNameGeneration(DisplayNameGenerator.Simple.class)
// @DisplayNameGeneration(DisplayNameGenerator.ReplaceUnderscores.class)
// @DisplayNameGeneration(DisplayNameGenerator.IndicativeSentences.class)
class AppTest {
	@BeforeAll
	static void initAll() {
	}

	@BeforeEach
	void init() {
	}

	@DisplayName("Test Assert Equals")
	@Test
	void testAssertEquals() {
		Double[] score = { 8.3, 4.5 };
		Double res = new App().getMedScore(score);
		final Double EXP = 6.4;
		assertEquals(EXP, res, "Falha no teste de verificação de sucesso na pontuação.");
	}

	@DisplayName("Test Assert True")
	@Test
	void testAssertTrue() {
		Double[] score = { 4.1, 5.5 };
		Double res = new App().getMedScore(score);
		final Double EXP = 4.8;
		assertTrue(EXP != res, "Falha no teste de verificação de fracasso na pontuação.");
	}

	@Test
	void testAssertInstanceOf() {
		Double[] score = { 4.7, 5.3 };
		assertInstanceOf(Long.class, new App().getMedScore(score).longValue(),
				"Falha no teste de verificação de inteiro.");
	}

	// Assumptions
	@Test
	void testAssume() {
		// Condição de execução do teste
		Double[] score = {};
		assumeFalse(score.length == 0, "Requisitos insuficientes para a execução do teste.");

		// Teste
		assertNotEquals(10.0, new App().getMedScore(score),
				"Falha no teste de verificação de valores informados.");
	}

	// Exception Handling
	@Test
	void testUncaughtException() {
		new App().getMedScore(Double.valueOf("A.A"));
	}

	@Test
	void testExceptionThrows() {
		// Verifica a classe superior e subclasse
		// RuntimeException -> IllegalArgumentException -> NumberFormatException
		assertThrows(RuntimeException.class, () -> {
			new App().getMedScore(Double.valueOf("A.C"));
		}, "Falha no teste de verificação de exceção.");
	}

	@Test
	void testExceptionThrowsExactly() {
		// Somente a classe informada
		// IllegalArgumentException -> NumberFormatException
		assertThrowsExactly(IllegalArgumentException.class, () -> {
			new App().getMedScore(Double.valueOf("E.10"));
		}, "Falha no teste de verificação de exceção específica.");
	}

	@Test
	void testExceptionDoesNotThrow() {
		// SEM exceção, então OK
		assertDoesNotThrow(() -> Long.valueOf("105"),
				"Falha no teste de verificação de NÃO exceção.");
	}

	// Disabling Tests
	@Test
	@Disabled
	void testDisabled() {
		// Teste com resultado ERRADO, mas que NÃO será executado
		assertTrue(Integer.valueOf(1).equals(Character.valueOf('K')),
				"Falha na verificação de igualdade de valores.");
	}

	// Conditional Test Execution - Internal
	@Test
	@EnabledIf("executeCondition")
	void testCustomInternalCondition() {
		assertDoesNotThrow(() -> Float.valueOf("25.6k"),
				"Falha no teste interno de conversão de valores.");
	}

	boolean executeCondition() {
		return false;
	}

	// Conditional Test Execution - External
	@Test
	@DisabledIf("org.theunit.App#disableTestCondition")
	void testCustomExternalCondition() {
		assertThrows(NumberFormatException.class, () -> Double.valueOf("15.9E"),
				"Falha no teste externo de conversão de valores.");
	}

	// Tag PRÓPRIA com @Test
	@MyTagTest(autor = "John")
	void testMyTag() {
		assertTimeout(Duration.ofNanos(1), () -> {
			final long MAX = 10000;
			for (long idx = 0; idx < MAX; idx++) {

			}
		}, "Falha no teste de verificação de tempo de processamento.");
	}

	// Nested Tests
	@Nested
	class SubAppTest {
		static Integer count = 1;
		Float valor;

		@BeforeEach
		void init() {
			this.valor = 10.5f;
		}

		@Test
		void executeSubTestSuccess() {
			System.out.printf("Método %d da Classe Aninhada.%n", count);
			assertEquals(Float.valueOf(10.5f), this.valor,
					"Falha no teste de verificação de valor na Classe Aninhada.");
		}

		@Test
		void executeSubTestError() {
			System.out.printf("Método %d da Classe Aninhada.%n", count);
			assertNotEquals(Float.valueOf(10.5f), this.valor,
					"Falha no teste de verificação de valor na Classe Aninhada.");
		}

		@AfterEach
		void tearDown() {
			count++;
		}
	}

	// Repeated Tests
	final String MODEL_TITLE = "{displayName} {currentRepetition} of {totalRepetitions}";

	@RepeatedTest(value = 5, name = MODEL_TITLE)
	void testRepetition(RepetitionInfo info) {
		assertEquals(0, info.getCurrentRepetition() % 2,
				"Falha no teste de repetição.");
	}

	@RepeatedTest(value = 5, failureThreshold = 2, name = MODEL_TITLE)
	void testRepetitionWithSkip(RepetitionInfo info) {
		assertEquals(0, info.getCurrentRepetition() % 2,
				"Falha no teste de repetição.");
	}

	// Parameterized Classes and Tests
	@Nested
	@ParameterizedClass
	@ValueSource(longs = { 20, 17 })
	class testParameterizedClassValueSourceOne {
		@Parameter
		long idade;

		@Test
		void testCheckAdult() {
			assertTrue(idade >= 18,
					"Falha no teste de verificação de maior idade.");
		}
	}

	@Nested
	class testParameterizedClassValueSourceTwo {
		@ParameterizedTest
		@ValueSource(longs = { 15, 8 })
		void testCheckChild(long nIdade) {
			assertTrue(nIdade <= 12,
					"Falha no teste de verificação de menor idade para criança.");
		}
	}

	// CsvSource
	@Nested
	@ParameterizedClass
	@CsvSource(delimiter = ';', value = {
			"Toyota Pr 2026; 19500.10",
			"Mercedes Bens 2025; 20450.55" })
	class testParameterizedClassCsvSourceOne {
		@Parameter(value = 0)
		String marca;

		@Parameter(value = 1)
		Double preco;

		@Test
		void testMaximumPrice() {
			assertTrue(preco <= 19700,
					"Falha na verificação de limite máximo de preço de compra de carro.");
		}
	}

	@Nested
	class testParameterizedClassCsvSourceTwo {
		@ParameterizedTest
		@CsvSource(delimiter = ';', value = {
				"1035-A-45; C",
				"1027-G-95; E"
		})
		void testMinimumDriverLicense(String regLicense, String catLicense) {
			assertEquals("E", catLicense, "Falha na verificação de permissão de direção para carreta.");
		}
	}

	// Sources of Arguments
	@Nested
	class testSourcesOfArguments {
		// ValueSource
		@ParameterizedTest
		@ValueSource(classes = { String.class })
		void testForValueSource(Class<?> caracter) {
			assertNotEquals(String.class, caracter.getClass(),
					"Falha na verificação de tipos de objeto.");
		}

		// NullSource e EmptySource
		@ParameterizedTest
		@EmptySource
		void testEmptySource(String carName) {
			assertTrue(carName.isEmpty(),
					"Falha na verificação da identificação da marca do carro.");
		}

		@ParameterizedTest
		@NullSource
		void testNullSource(Integer carAge) {
			assertTrue(carAge == null,
					"Falha na verificação da identificação do ano do carro.");
		}

		// EnumSource
		enum DaysOfTheWeek {
			SUN, MON, TUE, WED, THU, FRI, SAT
		}

		enum WorkingDays {
			MON, TUE, WED, THU, FRI
		}

		@ParameterizedTest
		@EnumSource(from = "THU", to = "SAT", value = DaysOfTheWeek.class)
		void testEnumSource(DaysOfTheWeek days) {
			assertDoesNotThrow(() -> {
				WorkingDays.valueOf(days.name());
			}, "Falha na verificação de dias de trabalho.");
		}

		// CsvFileSource
		@ParameterizedTest
		@CsvFileSource(resources = "/employer.csv", useHeadersInDisplayName = false, numLinesToSkip = 1)
		void testCsvFileSource(Integer employerID, String employerName, Double employerSalary) {
			assertTrue(employerSalary > Double.valueOf(10000.00),
					"Falha na verificação de faixa salarial aceitável.");

			System.out.printf("ID: %d; Name: %s; Salary: %.02f || ", employerID, employerName, employerSalary);
		}
	}

	// Argument Count Validation
	@ParameterizedTest(argumentCountValidation = ArgumentCountValidationMode.STRICT, name = "testArgsCountValidation")
	@CsvSource(value = { "Maria; Sampaio" }, delimiter = ';')
	void testArgsCountValidation(String name) {
		// Erro ao tentar executar
	}

	// Argument Conversion
	// Implicit
	static class SubClassVehicle {
		private String placa;

		private SubClassVehicle(String placa) {
			this.placa = placa;
		}

		String getPlaca() {
			return this.placa;
		}

		// Público e Estático para Instanciação do Objeto (Exemplo)
		static SubClassVehicle factory(String placa) {
			return new SubClassVehicle(placa);
		}
	}

	@ParameterizedTest(name = "testImplicitConv")
	@ValueSource(strings = "DDR9F455")
	void testImplicitConv(SubClassVehicle veiculo) {
		assertEquals("DDR9F455", veiculo.getPlaca(),
				"Falha na verificação de emplacamento de veiculo.");
	}

	// Explicit
	static class SubClassMotorcycle extends SimpleArgumentConverter {
		@Override
		protected Object convert(Object source, Class<?> targetType) {
			if (source instanceof String args) {
				if (!args.matches("^[0-9]")) {
					return args;
				} else {
					return Integer.valueOf(args);
				}
			}
			return null;
		}
	}

	@ParameterizedTest(name = "testExplicitConv")
	@CsvSource(value = "Mercedez XL 2025,3")
	void testExplicitConv(
			@ConvertWith(value = SubClassMotorcycle.class) String modelo,
			@ConvertWith(value = SubClassMotorcycle.class) Integer qtdRoda) {
		assertTrue(qtdRoda.equals(Integer.valueOf(2)) || qtdRoda.equals(Integer.valueOf(3)),
				"Falha na verificação de quantidade de rodas da motocicleta.");
	}

	// Argument Aggregation
	static class SubClassPhone {
		private String marca;
		private Double preco;

		SubClassPhone(String marca, Double preco) {
			this.marca = marca;
			this.preco = preco;
		}

		String getMarca() {
			return this.marca;
		}

		Double getPreco() {
			return this.preco;
		}
	}

	// With Arguments Accessor
	@ParameterizedTest
	@CsvSource(value = {
			"IPhone X5, 5990.99",
			"Motorola KL5, 4995.80" })
	void testWithArgumentsAccessor(ArgumentsAccessor args) {
		var phone = new SubClassPhone(args.getString(0),
				args.get(1, Double.class));

		assertTrue(phone.getPreco() <= Double.valueOf(5000.0),
				"Falha na verificação do cadastro de promoção de smartphone.");
	}

	// With Custom Aggregators
	static class SubArgumentsAggregatorPhone extends SimpleArgumentsAggregator {
		protected Object aggregateArguments(
				ArgumentsAccessor accessor,
				Class<?> targetType,
				AnnotatedElementContext context,
				int parameterIndex) {

			return new SubClassPhone(
					accessor.getString(0),
					accessor.get(1, Double.class));
		}
	}

	@ParameterizedTest
	@CsvSource(value = "Samsung KZ7, 7989.99")
	void testWithCustomAggregators(
			@AggregateWith(SubArgumentsAggregatorPhone.class) SubClassPhone phone) {

		assertTrue(phone.getMarca().toUpperCase().substring(0, 7).equals("SAMSUNG"),
				"Falha na verificação da marca do smartphone Samsung.");
	}

	// Customizing Display Names
	@DisplayName(value = "Test Rent City")
	@ParameterizedTest(name = "{displayName} => Reg. {index} => City {0}; Price {1}")
	@CsvSource(value = {
			"New York, 1450.95",
			"San Diego, 1200.10"
	})
	void testCustomDisplayName(String city, Double price) {
		final Double MAX_PROMO = Double.valueOf(1000.0);
		assertFalse(price <= MAX_PROMO, "Falha na verificação de aluguel.");
	}

	// Onde PAREI
	// https://docs.junit.org/6.0.1/writing-tests/timeouts.html

	@AfterEach
	void tearDown() {
	}

	@AfterAll
	static void tearDownAll() {
	}
}
